### ISSUE TITLE
Cassandra builds up large commit log then cannot start up

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/clearwater-cassandra#12]
Seen while cutting PacMan release, Cassandra (on the staging system) had built up a large backlog of unstored changes.  This lead to cassandra booting up, seeing the commit log, attempting to stream it into the database, running out of disk space, dying (or being killed by monit), restarting and finding the same commit log waiting for it - death spiral.

Lossily resolved by destroying and re-creating the `/var/lib/cassandra/data` folder.

**Comment by rkd-msw** [comment]
@bossmc - have we seen this since switching to 2.0.14? If not, should we close until and unless we see it on the current version?

**Comment by bossmc** [comment]
Not that I'm aware of, closing.
