### ISSUE TITLE
The restore_backup script doesn't work when run in the signaling namespace

### ISSUE THREAD

**Issue by AME2** [Metaswitch/clearwater-cassandra#122]
I've been following section 4.9 of the Clearwater Core Deployment Guide in an attempt to test the backup/restore procedure for Homestead-prov's data stores.

I created a Homestead-prov deployment and provisioned a subscriber using Homestead-prov's create_user script. I then used the do_backup script to create a backup which should have contained the provisioned subscriber's details.

Then by using scp I transferred the backup files onto a Homestead-prov node in a completely new deployment. I then ran the restore_backup script from the signalling namespace (as the document advises) pointing it at the backup files I had scp'ed onto the new Homestead-prov node.

I was expecting to see output of the following form:

```
Will attempt to backup from backup 1372336442947
Will attempt to backup from directory /home/ubuntu/bkp_test/
Found backup directory /home/ubuntu/bkp_test//1372336442947
Restoring backup for keyspace homestead_provisioning...
xss = -ea -javaagent:/usr/share/cassandra/lib/jamm-0.2.5.jar -XX:
+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms826M -Xmx826M -Xmn100M
-XX:+HeapDumpOnOutOfMemoryError -Xss180k
Clearing commitlog...
filter_criteria: Deleting old .db files...
filter_criteria: Restoring from backup: 1372336442947
private_ids: Deleting old .db files...
private_ids: Restoring from backup: 1372336442947
public_ids: Deleting old .db files...
public_ids: Restoring from backup: 1372336442947
sip_digests: Deleting old .db files...
sip_digests: Restoring from backup: 1372336442947
```

#### Symptoms
What I actually saw when I ran the restore_backup script was the following output:

```
Will attempt to restore from backup 1484243886338
Will attempt to restore from directory /tmp/backup/
Found backup directory /tmp/backup//1484243886338
Restoring backup for keyspace homestead_provisioning...
Cannot create socket to [localhost]:2812 -- Connection refused
Clearing commitlog...
implicit_registration_sets-2e2ec920d8e411e6816f95ab69150052: Deleting old .db files...
implicit_registration_sets-2e2ec920d8e411e6816f95ab69150052: Restoring from backup: 1484243886338
private-2e821940d8e411e6816f95ab69150052: Deleting old .db files...
private-2e821940d8e411e6816f95ab69150052: Restoring from backup: 1484243886338
public-2e60fcb0d8e411e6816f95ab69150052: Deleting old .db files...
public-2e60fcb0d8e411e6816f95ab69150052: Restoring from backup: 1484243886338
service_profiles-2e4de9e0d8e411e6816f95ab69150052: Deleting old .db files...
service_profiles-2e4de9e0d8e411e6816f95ab69150052: Restoring from backup: 1484243886338
Cannot create socket to [localhost]:2812 -- Connection refused
```

It looks like the script fails at the line:

`monit unmonitor -g cassandra`

This is because usually monit would normally use port 2812 to unmonitor a group of processes, however in the signaling namespace monit does not listen on port 2812. 

I think the script should be changed so that only the relevant commands are run in the signaling namespace and then the docs should be changed as a result to instruct users to run this script in the management namespace.

#### Impact
If a customer were using homestead-prov with regular backups and they lose their deployment they would not be able to restore the subscribers provisioned against that deployment. This could cause a large loss of service.

#### Release and environment 
CC-homestead,homestead-prov-10.0.0-170112-~255.00.0.ova
CC-ralf-10.0.0-170112-~255.00.0.ova
CC-sprout-10.0.0-170112-~255.00.0.ova

#### Steps to reproduce
Create a deployment with at least one Homestead-prov node. Run the following command to create a backup:

`sudo /usr/share/clearwater/bin/run-in-signaling-namespace /usr/share/clearwater/bin/do_backup.sh homestead_provisioning`

Make a note of the snapshot directory, <snapshot>. Then run the following command to restore the backup:

`sudo /usr/share/clearwater/bin/run-in-signaling-namespace /usr/share/clearwater/bin/restore_backup.sh homestead_provisioning <snapshot> <backup directory>`

**Comment by eleanor-merry** [comment]
This has been fixed by https://github.com/Metaswitch/clearwater-readthedocs/pull/239. Passing back for retest.

**Comment by AME2** [comment]
I've retested and can confirm this is now fixed.
