### ISSUE TITLE
There's an install race between cassandra and clearwater-cassandra

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-cassandra#17]
When installing homestead on a virgin machine, I where /etc/cassandra/cassandra-env.sh contained only this line:
```
JSVC="$JSVC" # clearwater-infrastructure
```
This turned out to be caused by clearwater-cassandra editing /etc/cassandra/cassandra-env.sh before cassandra had installed the default version of that file.

**Comment by mirw** [comment]
I think this is a duplicate of #16.  I don't think clearwater-cassandra should modify /etc/cassandra/cassandra-env.sh - this is going to cause package upgrade headaches in future.
