### ISSUE TITLE
Cassandra 2.0 doesn't run in the signalling netns

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-cassandra#37]
Cassandra 2.0's new init.d script doesn't make use of JSVC variable set in /etc/cassandra-env.sh, so it doesn't run in the correct net namespace when using multiple interfaces.

**Comment by eleanor-merry** [comment]
Cassandra 2.0 now uses the start-stop-daemon, not JSVC (see https://issues.apache.org/jira/browse/CASSANDRA-3991). 
Fix is to change the cassandra script (https://github.com/Metaswitch/clearwater-cassandra/blob/master/clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra) to modify the init.d script, not the cassandra-env.s script (need to update #16 )
