### ISSUE TITLE
The cassandra schemas aren't always being added

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/clearwater-cassandra#54]
The poll_cassandra script has a grace period, and we return OK during this time. This means that we try to add the schemas too early in the clustering process. The Homestead schemas get added OK because we have a 2 minute delay in the schema creation - other cassandra schemas don't get added. 

We should also fix up the schema creation scripts so that they use poll_cassandra to check if cassandra is up before running.

**Comment by JimBunch** [comment]
Marking as critical because the CCF will not be installed correctly.

**Comment by eleanor-merry** [comment]
Fixed by linked PRs
