### ISSUE TITLE
cassandra is still running after decommission 

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-cassandra#58]
After decommissioning a homestead/homestead-prov node, I noticed that Cassandra was still running and still a member of the ring.

Diags are available.

**Comment by eleanor-merry** [comment]
The cassandra plugin is attempting to run `nodetool decommissionip netns exec signaling nodetool decommission`. It looks like the fault is in https://github.com/Metaswitch/clearwater-etcd/blob/master/src/metaswitch/clearwater/etcd_shared/plugin_utils.py#L50 using a `+=` not a `=`, but this hasn't been changed for quite a while. 

Had you seen decommissioning work before this?

**Comment by eleanor-merry** [comment]
(Decommissioning on a multiple network system that is)

**Comment by dtheobald** [comment]
I just started testing scale up/down late last week and just got to homestead decommissioning today. Prior to today, I hadn't decommissioned anything a quite a while.

**Comment by eleanor-merry** [comment]
Okeydoke, @dtheobald passing back to you for retest

**Comment by dtheobald** [comment]
Fixed
