### ISSUE TITLE
CASSANDRA_NOT_YET_CLUSTERED alarm is not cleared after rebooting

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-cassandra#61]
CASSANDRA_NOT_YET_CLUSTERED is not cleared after rebooting a node that's already in a cluster (i.e. the node is not newly joining a cluster). To temporarily fix this, I made the following change to cassandra_plugin.py:

```
diff --git a/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py b/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
index de797b2..c242c3f 100644
--- a/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
+++ b/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
@@ -194,6 +194,8 @@ class CassandraPlugin(SynchroniserPluginBase):
         pass
 
     def on_stable_cluster(self, cluster_view):
+        _log.debug("Clearing Cassandra not-clustered alarm")
+        issue_alarm(alarm_constants.CASSANDRA_NOT_YET_CLUSTERED_CLEARED)
         pass
 
     def on_leaving_cluster(self, cluster_view):
```

**Comment by mirw** [comment]
Marking as high priority as we need a permanent solution as soon as possible.

**Comment by rkd-msw** [comment]
Feels like the permanent, general-case fix is to have a `clear_alarms(process)` call in https://github.com/Metaswitch/python-common/blob/dev/metaswitch/common/alarms.py#L48, the equivalent of https://github.com/Metaswitch/cpp-common/blob/abb9fc5d0f593b78b7139c4cbc6a2877d2676930/src/alarm.cpp#L67, and just call that on startup in each Python component.

**Comment by rkd-msw** [comment]
Actually, maybe that doesn't help in this case - we'd then create the plugin and re-raise it. But it's a sensible thing to do anyway.
