### ISSUE TITLE
Cassandra failed plugin doesn't work for multiple networks

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/clearwater-cassandra#69]
Plugin is at https://github.com/Metaswitch/clearwater-cassandra/blob/master/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/failed_plugins/cassandra_failed_plugin.py - it just needs run_in_signalling_namespace adding to the nodetool commands

**Comment by chris-elford-metaswitch** [comment]
Issue fixed by the pull request.
