### ISSUE TITLE
run_cassandra_schemas script runs non-executable schema scripts

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-cassandra#71]
The ```/usr/share/clearwater/cassandra-schemas``` directory contains a non-executable file ```replication_string.sh``` which mistakenly gets run by ```run_cassandra_schemas```.

**Comment by rkd-msw** [comment]
Fixed by https://github.com/Metaswitch/clearwater-cassandra/pull/75/files, which moves the code out of that directory.
