### ISSUE TITLE
Cassandra locks up due to running out of heap space

### ISSUE THREAD

**Issue by mirw** [Metaswitch/clearwater-cassandra#8]
I saw Cassandra lock up (using up 100% CPU and failing connections from homestead and `cqlsh`), apparently because the heap was full.  However, we weren't really storing any data in Cassandra (2 subscribers/4 rows at most), so it's hard to see why it's hitting this.

```
WARN 06:41:03,346 Heap is 0.9999962840897153 full.  You may need to reduce memtable and/or cache sizes.  Cassandra will now flush up to the two largest memtables to free up memory.  Adjust flush_largest_memtables_at threshold in cassandra.yaml if you don't want Cassandra to do this automatically
INFO 06:41:09,182 Unable to reduce heap usage since there are no dirty column families
INFO 06:41:18,646 GC for ConcurrentMarkSweep: 216445 ms for 81 collections, 1052767192 used; max is 1052770304
INFO 06:41:21,006 Pool Name                    Active   Pending      Completed   Blocked  All Time Blocked
INFO 06:41:32,442 ReadStage                         0         0            382         0                 0
INFO 06:41:40,417 RequestResponseStage              0         0              2         0                 0
INFO 06:41:44,698 ReadRepairStage                   0         0              0         0                 0
INFO 06:41:48,981 MutationStage                     0         0            211         0                 0
INFO 06:41:56,943 ReplicateOnWriteStage             0         0              0         0                 0
INFO 06:42:02,754 GossipStage                       0         0              0         0                 0
INFO 06:42:10,708 AntiEntropyStage                  0         0              0         0                 0
INFO 06:42:18,659 MigrationStage                    0         0              0         0                 0
INFO 06:42:24,475 MemtablePostFlusher               0         0           7032         0                 0
INFO 06:42:30,875 MemoryMeter                       0         0              0         0                 0
INFO 06:42:36,893 FlushWriter                       0         0             10         0                 0
INFO 06:42:42,496 MiscStage                         0         0              0         0                 0
INFO 06:42:48,938 PendingRangeCalculator            0         0              1         0                 0
INFO 06:42:54,749 commitlog_archiver                0         0              0         0                 0
INFO 06:43:02,704 InternalResponseStage             0         0              0         0                 0
INFO 06:43:14,525 HintedHandoff                     0         0              0         0                 0
INFO 06:43:22,495 CompactionManager                 0         0
INFO 06:43:28,089 Commitlog                       n/a         0
INFO 06:43:31,773 MessagingService                n/a       0/0
INFO 06:43:36,056 Cache Type                     Size                 Capacity               KeysToSave                                                         Provider
INFO 06:43:39,751 KeyCache                        680                      720                      all                                                     
 INFO 06:43:45,560 RowCache                          0                        0                      all              org.apache.cassandra.cache.SerializingCacheProvider
INFO 06:43:47,703 ColumnFamily                Memtable ops,data
INFO 06:43:53,522 system.local                              0,0
INFO 06:43:57,199 system.peers                              0,0
INFO 06:43:59,344 system.batchlog                           0,0
INFO 06:44:03,010 system.NodeIdInfo                         0,0
INFO 06:44:05,378 system.LocationInfo                       0,0
INFO 06:44:08,836 system.Schema                             0,0
INFO 06:44:14,636 system.Migrations                         0,0
INFO 06:44:14,651 system.schema_keyspaces                   0,0
INFO 06:44:20,474 system.schema_columns                     0,0
INFO 06:44:22,580 system.schema_columnfamilies                 0,0
INFO 06:44:24,672 system.IndexInfo                          0,0
INFO 06:44:24,673 system.range_xfers                        0,0
INFO 06:44:26,993 system.peer_events                        0,0
INFO 06:44:30,424 system.hints                              0,0
INFO 06:44:32,569 system.HintsColumnFamily                  0,0
INFO 06:44:34,680 homestead_cache.impu                      0,0
INFO 06:44:36,774 homestead_cache.impi                      0,0
INFO 06:44:39,076 system_traces.sessions                    0,0
INFO 06:44:42,482 system_traces.events                      0,0
```

**Comment by rekhajoshm** [comment]
Hi,

On DSE 4.5.1, Java 1.7, linux encountered long running GC before dse was shutdown.
This was a ring of 6 nodes, and no unexpected load/processes were run.The error log attached.

What are the flush/cache params in 4.5.1?I can check if they are configured.
My first suspect was that it has hit hotspot/java GC issue.But in this case the class unloading is enabled.
JVM_OPTS="$JVM_OPTS -XX:+CMSClassUnloadingEnabled”
XX:CMSInitiatingOccupancyFraction=75

Now configured to have MAX_HEAP_SIZE=“8G”, HEAP_NEWSIZE=“2G” and GC logging enabled and it is stable for a while now.But I am not certian when the GC issue will hit again.

Thanks
Rekha
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,120 GCInspector.java (line 116) GC for ConcurrentMarkSweep: 22588 ms for 1 collections, 7872534648 used; max is 7981760512
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,121 StatusLogger.java (line 55) Pool Name                    Active   Pending      Completed   Blocked  All Time Blocked
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,121 StatusLogger.java (line 70) ReadStage                        12        12     2561243498         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,121 StatusLogger.java (line 70) RequestResponseStage              0         0     1430694184         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,122 StatusLogger.java (line 70) ReadRepairStage                   0         0       70671943         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,122 StatusLogger.java (line 70) MutationStage                     0         0       30160663         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,122 StatusLogger.java (line 70) ReplicateOnWriteStage             0         0              0         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,122 StatusLogger.java (line 70) GossipStage                       0         0        4466976         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,122 StatusLogger.java (line 70) CacheCleanupExecutor              0         0              0         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,123 StatusLogger.java (line 70) MigrationStage                    0         0              1         0                 0
system.log- WARN [WRITE-/] 2015-02-27 22:34:25,123 SSLFactory.java (line 139) Filtering out TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA as it isnt supported by the socket
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,123 StatusLogger.java (line 70) MemoryMeter                       0         0          12033         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,123 StatusLogger.java (line 70) ValidationExecutor                0         0          18734         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,124 StatusLogger.java (line 70) FlushWriter                       0         0           8326         0                11
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,124 StatusLogger.java (line 70) InternalResponseStage             0         0              9         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,124 StatusLogger.java (line 70) AntiEntropyStage                  0         0          59688         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,124 StatusLogger.java (line 70) MemtablePostFlusher               0         0          47185         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,125 StatusLogger.java (line 70) MiscStage                         0         0              0         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,125 StatusLogger.java (line 70) PendingRangeCalculator            0         0             54         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,125 StatusLogger.java (line 70) CompactionExecutor                1         1          19099         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,125 StatusLogger.java (line 70) commitlog_archiver                0         0              0         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,125 StatusLogger.java (line 70) AntiEntropySessions               0         0            192         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 70) HintedHandoff                     1         1            152         0                 0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 79) CompactionManager                 1         1
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 81) Commitlog                       n/a         0
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 93) MessagingService                n/a       0/6
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 103) Cache Type                     Size                 Capacity               KeysToSave
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 105) KeyCache                  104857600                104857600                      all
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,126 StatusLogger.java (line 111) RowCache                          0                        0                      all
system.log- INFO [ScheduledTasks:1] 2015-02-27 22:34:25,127 StatusLogger.java (line 118) ColumnFamily                Memtable ops,data
system.log: INFO [Thread-39] 2015-02-27 22:34:48,059 DseDaemon.java (line 477) DSE shutting down...

**Comment by eleanor-merry** [comment]
Hi,

Just a heads-up that this isn't the master Cassandra repository - this is a git repository containing various wrapper scripts for Cassandra that we use as part of [Project Clearwater](http://www.projectclearwater.org/). Are you hitting this on a Clearwater deployment - if so can you please provide some information about the Clearwater deployment you're using?

Otherwise, you might have more luck over on the Cassandra mailing list at http://www.mail-archive.com/user@cassandra.apache.org/.

Ellie

**Comment by rekhajoshm** [comment]
ok this is master cassandra.thanks @eleanor-merry

**Comment by eleanor-merry** [comment]
Hi,

Just a heads-up that this isn't the master Cassandra repository - this is a git repository containing various wrapper scripts for Cassandra that we use as part of [Project Clearwater](http://www.projectclearwater.org/). Are you hitting this on a Clearwater deployment - if so can you please provide some information about the Clearwater deployment you're using?

Otherwise, you might have more luck over on the Cassandra mailing list at http://www.mail-archive.com/user@cassandra.apache.org/.

Ellie
