### ISSUE TITLE
Cassandra can get into an unmonitored state so clustering fails

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/clearwater-cassandra#96]
#### Symptoms
During the cassandra clustering process, we [unmonitor](https://github.com/Metaswitch/clearwater-cassandra/blob/master/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py#L166) and [remonitor](https://github.com/Metaswitch/clearwater-cassandra/blob/master/clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py#L235) cassandra.

There's a gap between monit accepting a request to monitor a process, and it actually monitoring the process (I've seen up to a second in the logs). Monit can be restarted during this time - which isn't that unlikely on a new install as all our packages restart monit in their postinsts. If it is, we get into a bad state where cassandra isn't monitored (as monit has lost the fact it was midway through monitoring it), but the cluster manager thinks casssandra is monitored (as monit returned OK to our request to monitor cassandra). The cluster manager then sits testing if cassandra is up every second and never progresses with the clustering process.

#### Impact
Cassandra clustering can fail. A workaround is to stop the clearwater-cluster-manager (and let monit restart it).

#### Release and environment 
Seen in the Charizard release (but the relevant code is older than this).

**Comment by rkd-msw** [comment]
I've got an outstanding thing (which I'll do this sprint) to rework that code, so it:
* deletes /etc/cassandra/cassandra.yaml and stops Cassandra
* expects the lack of cassandra.yaml to stop Cassandra from restarting (https://github.com/Metaswitch/clearwater-cassandra/blob/master/clearwater-cassandra/etc/init.d/cassandra.clearwater#L27) even though it hasn't been explicitly unmonitored
* reinstates /etc/cassandra/cassandra.yaml as the last step so Cassandra can start again

I'm doing this so I can pull clearwater-cluster-manager into Docker without Monit (https://github.com/Metaswitch/clearwater-docker/pull/19#discussion_r56764789), but I think it will fix this problem too?

**Comment by eleanor-merry** [comment]
Sounds good to me
